name: Sync Gitee Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: morbalint/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source_repo: "git@github.com:Yu-Core/SwashbucklerDiary.git"
        destination_repo: "git@gitee.com:Yu-core/SwashbucklerDiary.git"
        branches: "gh-pages"
        force_push_branches: true

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: Yu-core
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: Yu-core/SwashbucklerDiary
          branch: gh-pages
